### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by oviniciuslara** [agashe/Small-LCD-Driver---ATmega32#1]
You can show the connections hardware?

I'm using Arduino UNO and a 20x4 LCD.

**Comment by agashe** [comment]
Here is my connections with Atmega32:

![lcd](https://user-images.githubusercontent.com/12908115/40964099-84cd6c4e-68aa-11e8-91a0-6597a537cd25.jpg)

for Arduino, i think it will be something like  this:
http://www.electronicwings.com/arduino/lcd-16x2-interfacing-with-arduino-uno

The LCD size doesn't affect the connections!
